import = [
    "~/.config/alacritty/themes/themes/terminal_app.toml"
]

# [env]
# TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

[window]
padding = { x = 0, y = 0 }
decorations = "none"
opacity = 1
# opacity = 0.8
# blur = true

[font]
size = 16

  [font.normal]
  family = "JetbrainsMono Nerd Font Mono"
