
[colors]
draw_bold_text_with_bright_colors = true

[window]
decorations = "none"
opacity = 1

[font]
size = 15

  [font.normal]
  family = "JetbrainsMono Nerd Font Mono"

[colors.primary]
background = '#282828'
foreground = '#d4be98'

# Normal colors
[colors.normal]
black   = '#3c3836'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'

# Bright colors (same as normal colors)
[colors.bright]
black   = '#3c3836'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'

# [colors.primary]
# background = "0x1f1f28"
# foreground = "0xdcd7ba"
#
# [colors.normal]
# black = "0x090618"
# red = "0xc34043"
# green = "0x76946a"
# yellow = "0xc0a36e"
# blue = "0x7e9cd8"
# magenta = "0x957fb8"
# cyan = "0x6a9589"
# white = "0xc8c093"
#
# [colors.bright]
# black = "0x727169"
# red = "0xe82424"
# green = "0x98bb6c"
# yellow = "0xe6c384"
# blue = "0x7fb4ca"
# magenta = "0x938aa9"
# cyan = "0x7aa89f"
# white = "0xdcd7ba"

[colors.selection]
background = "0x2d4f67"
foreground = "0xc8c093"

[[colors.indexed_colors]]
index = 16
color = "0xffa066"

[[colors.indexed_colors]]
index = 17
color = "0xff5d62"

